name: mls_player_compare
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+11

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  screenshot: ^3.0.0
  share_plus: ^10.0.0
  fl_chart: ^0.70.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/stathead_FC.jpg

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/stathead_FC.jpg"
  min_sdk_android: 21